services:
  devcontainer:
    # image: node:lts
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    ports:
      - 3000:3000
    environment:
      - ZEITY_DATABASE_URL=postgresql://postgres:postgres@postgres:5432/zeity
      - ZEITY_S3_END_POINT=http://storage:9000
      - ZEITY_MAILER_SMTP_HOST=maildev

  postgres:
    image: postgres:18
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: zeity
    volumes:
      - pg-data:/var/lib/postgresql

  storage:
    image: rustfs/rustfs
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      RUSTFS_ACCESS_KEY: storage
      RUSTFS_SECRET_KEY: storage123
    volumes:
      - storage-data:/data

  storage-init:
    image: minio/mc
    restart: "no"
    depends_on:
      - storage
    entrypoint: >
      sh -c "
        sleep 10 &&
        mc alias set local http://storage:9000 storage storage123 &&
        mc mb local/zeity --ignore-existing
      "

  maildev:
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

volumes:
  pg-data:
  storage-data:
